type Query {
	helloWorld: String
	addresses(from: Int!, to: Int!): AddressesRes
	addressesLen: Int
}

type Mutation {
	login(username: String!, password: String!): AuthPayload
	logout(token: String!): Boolean
	createAdresses(addresses: [MacAdressPayload!]!): [MacAdress]
	editAdress(id: Int!, edit: MacAdressPayloadEdit!): MacAdress
	deleteAdress(id: Int!): Boolean
}

type AddressesRes {
	range: Range
	total: Int	
	addresses: [MacAdress]
}

type Range {
	from: Int
	to: Int
}

type MacAdress {
	id: Int
	device_name: String
	user_name: String
	networkcard: String
	macAdress: MacAdressData
}

input MacAdressPayloadEdit {
	device_name: String
	user_name: String
	networkcard: String
	macAdress: MacAdressDataPayload
}

input MacAdressPayload {
	device_name: String!
	user_name: String
	networkcard: String!
	macAdress: MacAdressDataPayload!
}

input MacAdressDataPayload {
	sect1: Int!,
	sect2: Int!,
	sect3: Int!,
	sect4: Int!,
	sect5: Int!,
	sect6: Int!,
}

type MacAdressData {
	sect1: Int,
	sect2: Int,
	sect3: Int,
	sect4: Int,
	sect5: Int,
	sect6: Int,
}

type AuthPayload {
	token: String
	name: String
	expiresIn: Int
	permissions: [String]
}
